//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace EvolutionSimulator
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class EvolutionEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new EvolutionEntities object using the connection string found in the 'EvolutionEntities' section of the application configuration file.
        /// </summary>
        public EvolutionEntities() : base("name=EvolutionEntities", "EvolutionEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EvolutionEntities object.
        /// </summary>
        public EvolutionEntities(string connectionString) : base(connectionString, "EvolutionEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EvolutionEntities object.
        /// </summary>
        public EvolutionEntities(EntityConnection connection) : base(connection, "EvolutionEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<S_DNA> DNA
        {
            get
            {
                if ((_DNA == null))
                {
                    _DNA = base.CreateObjectSet<S_DNA>("DNA");
                }
                return _DNA;
            }
        }
        private ObjectSet<S_DNA> _DNA;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DPLANT> DPLANT
        {
            get
            {
                if ((_DPLANT == null))
                {
                    _DPLANT = base.CreateObjectSet<DPLANT>("DPLANT");
                }
                return _DPLANT;
            }
        }
        private ObjectSet<DPLANT> _DPLANT;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DGROUND> DGROUND
        {
            get
            {
                if ((_DGROUND == null))
                {
                    _DGROUND = base.CreateObjectSet<DGROUND>("DGROUND");
                }
                return _DGROUND;
            }
        }
        private ObjectSet<DGROUND> _DGROUND;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DMAP> DMAP
        {
            get
            {
                if ((_DMAP == null))
                {
                    _DMAP = base.CreateObjectSet<DMAP>("DMAP");
                }
                return _DMAP;
            }
        }
        private ObjectSet<DMAP> _DMAP;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DNA EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDNA(S_DNA s_DNA)
        {
            base.AddObject("DNA", s_DNA);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DPLANT EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDPLANT(DPLANT dPLANT)
        {
            base.AddObject("DPLANT", dPLANT);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DGROUND EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDGROUND(DGROUND dGROUND)
        {
            base.AddObject("DGROUND", dGROUND);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DMAP EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDMAP(DMAP dMAP)
        {
            base.AddObject("DMAP", dMAP);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dataModel", Name="DGROUND")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DGROUND : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DGROUND object.
        /// </summary>
        /// <param name="gROUND_ID">Initial value of the GROUND_ID property.</param>
        public static DGROUND CreateDGROUND(global::System.String gROUND_ID)
        {
            DGROUND dGROUND = new DGROUND();
            dGROUND.GROUND_ID = gROUND_ID;
            return dGROUND;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String GROUND_ID
        {
            get
            {
                return _GROUND_ID;
            }
            set
            {
                if (_GROUND_ID != value)
                {
                    OnGROUND_IDChanging(value);
                    ReportPropertyChanging("GROUND_ID");
                    _GROUND_ID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("GROUND_ID");
                    OnGROUND_IDChanged();
                }
            }
        }
        private global::System.String _GROUND_ID;
        partial void OnGROUND_IDChanging(global::System.String value);
        partial void OnGROUND_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PARENT
        {
            get
            {
                return _PARENT;
            }
            set
            {
                OnPARENTChanging(value);
                ReportPropertyChanging("PARENT");
                _PARENT = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PARENT");
                OnPARENTChanged();
            }
        }
        private global::System.String _PARENT;
        partial void OnPARENTChanging(global::System.String value);
        partial void OnPARENTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> X
        {
            get
            {
                return _X;
            }
            set
            {
                OnXChanging(value);
                ReportPropertyChanging("X");
                _X = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("X");
                OnXChanged();
            }
        }
        private Nullable<global::System.Int32> _X;
        partial void OnXChanging(Nullable<global::System.Int32> value);
        partial void OnXChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Y
        {
            get
            {
                return _Y;
            }
            set
            {
                OnYChanging(value);
                ReportPropertyChanging("Y");
                _Y = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Y");
                OnYChanged();
            }
        }
        private Nullable<global::System.Int32> _Y;
        partial void OnYChanging(Nullable<global::System.Int32> value);
        partial void OnYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> ABSORTION
        {
            get
            {
                return _ABSORTION;
            }
            set
            {
                OnABSORTIONChanging(value);
                ReportPropertyChanging("ABSORTION");
                _ABSORTION = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ABSORTION");
                OnABSORTIONChanged();
            }
        }
        private Nullable<global::System.Double> _ABSORTION;
        partial void OnABSORTIONChanging(Nullable<global::System.Double> value);
        partial void OnABSORTIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DAMAGE
        {
            get
            {
                return _DAMAGE;
            }
            set
            {
                OnDAMAGEChanging(value);
                ReportPropertyChanging("DAMAGE");
                _DAMAGE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DAMAGE");
                OnDAMAGEChanged();
            }
        }
        private Nullable<global::System.Int32> _DAMAGE;
        partial void OnDAMAGEChanging(Nullable<global::System.Int32> value);
        partial void OnDAMAGEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GROUNDTYPE
        {
            get
            {
                return _GROUNDTYPE;
            }
            set
            {
                OnGROUNDTYPEChanging(value);
                ReportPropertyChanging("GROUNDTYPE");
                _GROUNDTYPE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GROUNDTYPE");
                OnGROUNDTYPEChanged();
            }
        }
        private global::System.String _GROUNDTYPE;
        partial void OnGROUNDTYPEChanging(global::System.String value);
        partial void OnGROUNDTYPEChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dataModel", Name="DMAP")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DMAP : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DMAP object.
        /// </summary>
        /// <param name="mAP_ID">Initial value of the MAP_ID property.</param>
        public static DMAP CreateDMAP(global::System.String mAP_ID)
        {
            DMAP dMAP = new DMAP();
            dMAP.MAP_ID = mAP_ID;
            return dMAP;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MAP_ID
        {
            get
            {
                return _MAP_ID;
            }
            set
            {
                if (_MAP_ID != value)
                {
                    OnMAP_IDChanging(value);
                    ReportPropertyChanging("MAP_ID");
                    _MAP_ID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MAP_ID");
                    OnMAP_IDChanged();
                }
            }
        }
        private global::System.String _MAP_ID;
        partial void OnMAP_IDChanging(global::System.String value);
        partial void OnMAP_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ROWS
        {
            get
            {
                return _ROWS;
            }
            set
            {
                OnROWSChanging(value);
                ReportPropertyChanging("ROWS");
                _ROWS = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ROWS");
                OnROWSChanged();
            }
        }
        private Nullable<global::System.Int32> _ROWS;
        partial void OnROWSChanging(Nullable<global::System.Int32> value);
        partial void OnROWSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> COLUMNS
        {
            get
            {
                return _COLUMNS;
            }
            set
            {
                OnCOLUMNSChanging(value);
                ReportPropertyChanging("COLUMNS");
                _COLUMNS = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("COLUMNS");
                OnCOLUMNSChanged();
            }
        }
        private Nullable<global::System.Int32> _COLUMNS;
        partial void OnCOLUMNSChanging(Nullable<global::System.Int32> value);
        partial void OnCOLUMNSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MAPNAME
        {
            get
            {
                return _MAPNAME;
            }
            set
            {
                OnMAPNAMEChanging(value);
                ReportPropertyChanging("MAPNAME");
                _MAPNAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MAPNAME");
                OnMAPNAMEChanged();
            }
        }
        private global::System.String _MAPNAME;
        partial void OnMAPNAMEChanging(global::System.String value);
        partial void OnMAPNAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SAVEGAME
        {
            get
            {
                return _SAVEGAME;
            }
            set
            {
                OnSAVEGAMEChanging(value);
                ReportPropertyChanging("SAVEGAME");
                _SAVEGAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SAVEGAME");
                OnSAVEGAMEChanged();
            }
        }
        private global::System.String _SAVEGAME;
        partial void OnSAVEGAMEChanging(global::System.String value);
        partial void OnSAVEGAMEChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dataModel", Name="DPLANT")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DPLANT : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DPLANT object.
        /// </summary>
        /// <param name="aliveID">Initial value of the aliveID property.</param>
        public static DPLANT CreateDPLANT(global::System.String aliveID)
        {
            DPLANT dPLANT = new DPLANT();
            dPLANT.aliveID = aliveID;
            return dPLANT;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String aliveID
        {
            get
            {
                return _aliveID;
            }
            set
            {
                if (_aliveID != value)
                {
                    OnaliveIDChanging(value);
                    ReportPropertyChanging("aliveID");
                    _aliveID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("aliveID");
                    OnaliveIDChanged();
                }
            }
        }
        private global::System.String _aliveID;
        partial void OnaliveIDChanging(global::System.String value);
        partial void OnaliveIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PARENT_ID
        {
            get
            {
                return _PARENT_ID;
            }
            set
            {
                OnPARENT_IDChanging(value);
                ReportPropertyChanging("PARENT_ID");
                _PARENT_ID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PARENT_ID");
                OnPARENT_IDChanged();
            }
        }
        private global::System.String _PARENT_ID;
        partial void OnPARENT_IDChanging(global::System.String value);
        partial void OnPARENT_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CURRENTLIFECYCLE
        {
            get
            {
                return _CURRENTLIFECYCLE;
            }
            set
            {
                OnCURRENTLIFECYCLEChanging(value);
                ReportPropertyChanging("CURRENTLIFECYCLE");
                _CURRENTLIFECYCLE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CURRENTLIFECYCLE");
                OnCURRENTLIFECYCLEChanged();
            }
        }
        private Nullable<global::System.Int32> _CURRENTLIFECYCLE;
        partial void OnCURRENTLIFECYCLEChanging(Nullable<global::System.Int32> value);
        partial void OnCURRENTLIFECYCLEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> GENERATION
        {
            get
            {
                return _GENERATION;
            }
            set
            {
                OnGENERATIONChanging(value);
                ReportPropertyChanging("GENERATION");
                _GENERATION = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GENERATION");
                OnGENERATIONChanged();
            }
        }
        private Nullable<global::System.Int32> _GENERATION;
        partial void OnGENERATIONChanging(Nullable<global::System.Int32> value);
        partial void OnGENERATIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SIZE
        {
            get
            {
                return _SIZE;
            }
            set
            {
                OnSIZEChanging(value);
                ReportPropertyChanging("SIZE");
                _SIZE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SIZE");
                OnSIZEChanged();
            }
        }
        private Nullable<global::System.Int32> _SIZE;
        partial void OnSIZEChanging(Nullable<global::System.Int32> value);
        partial void OnSIZEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> NEXTREPRODUCTIONCYCLE
        {
            get
            {
                return _NEXTREPRODUCTIONCYCLE;
            }
            set
            {
                OnNEXTREPRODUCTIONCYCLEChanging(value);
                ReportPropertyChanging("NEXTREPRODUCTIONCYCLE");
                _NEXTREPRODUCTIONCYCLE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NEXTREPRODUCTIONCYCLE");
                OnNEXTREPRODUCTIONCYCLEChanged();
            }
        }
        private Nullable<global::System.Double> _NEXTREPRODUCTIONCYCLE;
        partial void OnNEXTREPRODUCTIONCYCLEChanging(Nullable<global::System.Double> value);
        partial void OnNEXTREPRODUCTIONCYCLEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> WATERDEPOSIT
        {
            get
            {
                return _WATERDEPOSIT;
            }
            set
            {
                OnWATERDEPOSITChanging(value);
                ReportPropertyChanging("WATERDEPOSIT");
                _WATERDEPOSIT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("WATERDEPOSIT");
                OnWATERDEPOSITChanged();
            }
        }
        private Nullable<global::System.Double> _WATERDEPOSIT;
        partial void OnWATERDEPOSITChanging(Nullable<global::System.Double> value);
        partial void OnWATERDEPOSITChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String STATUS
        {
            get
            {
                return _STATUS;
            }
            set
            {
                OnSTATUSChanging(value);
                ReportPropertyChanging("STATUS");
                _STATUS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("STATUS");
                OnSTATUSChanged();
            }
        }
        private global::System.String _STATUS;
        partial void OnSTATUSChanging(global::System.String value);
        partial void OnSTATUSChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dataModel", Name="S_DNA")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class S_DNA : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new S_DNA object.
        /// </summary>
        /// <param name="pARENT_ID">Initial value of the PARENT_ID property.</param>
        /// <param name="gEN">Initial value of the GEN property.</param>
        public static S_DNA CreateS_DNA(global::System.String pARENT_ID, global::System.String gEN)
        {
            S_DNA s_DNA = new S_DNA();
            s_DNA.PARENT_ID = pARENT_ID;
            s_DNA.GEN = gEN;
            return s_DNA;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PARENT_ID
        {
            get
            {
                return _PARENT_ID;
            }
            set
            {
                if (_PARENT_ID != value)
                {
                    OnPARENT_IDChanging(value);
                    ReportPropertyChanging("PARENT_ID");
                    _PARENT_ID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("PARENT_ID");
                    OnPARENT_IDChanged();
                }
            }
        }
        private global::System.String _PARENT_ID;
        partial void OnPARENT_IDChanging(global::System.String value);
        partial void OnPARENT_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String GEN
        {
            get
            {
                return _GEN;
            }
            set
            {
                if (_GEN != value)
                {
                    OnGENChanging(value);
                    ReportPropertyChanging("GEN");
                    _GEN = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("GEN");
                    OnGENChanged();
                }
            }
        }
        private global::System.String _GEN;
        partial void OnGENChanging(global::System.String value);
        partial void OnGENChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> VALOR
        {
            get
            {
                return _VALOR;
            }
            set
            {
                OnVALORChanging(value);
                ReportPropertyChanging("VALOR");
                _VALOR = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VALOR");
                OnVALORChanged();
            }
        }
        private Nullable<global::System.Double> _VALOR;
        partial void OnVALORChanging(Nullable<global::System.Double> value);
        partial void OnVALORChanged();

        #endregion

    
    }

    #endregion

    
}
