USE [master]
GO

/****** Object:  Database [DATA.MDF]    Script Date: 11/24/2017 12:08:36 PM ******/
CREATE DATABASE [DATA.MDF]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'data', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\data.mdf' , SIZE = 3328KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'data_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\data_log.ldf' , SIZE = 832KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [DATA.MDF] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DATA.MDF].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DATA.MDF] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DATA.MDF] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DATA.MDF] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DATA.MDF] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DATA.MDF] SET ARITHABORT OFF 
GO

ALTER DATABASE [DATA.MDF] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [DATA.MDF] SET AUTO_SHRINK ON 
GO

ALTER DATABASE [DATA.MDF] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DATA.MDF] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DATA.MDF] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DATA.MDF] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DATA.MDF] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DATA.MDF] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DATA.MDF] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DATA.MDF] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DATA.MDF] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DATA.MDF] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DATA.MDF] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DATA.MDF] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DATA.MDF] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DATA.MDF] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DATA.MDF] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DATA.MDF] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DATA.MDF] SET  MULTI_USER 
GO

ALTER DATABASE [DATA.MDF] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DATA.MDF] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DATA.MDF] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DATA.MDF] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [DATA.MDF] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DATA.MDF] SET QUERY_STORE = OFF
GO

USE [DATA.MDF]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [DATA.MDF] SET  READ_WRITE 
GO


