USE [DATA.MDF]
GO

/****** Object:  Table [dbo].[DMAP]    Script Date: 11/24/2017 12:10:41 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DMAP](
	[MAP_ID] [char](32) NOT NULL,
	[ROWS] [int] NULL,
	[COLUMNS] [int] NULL,
	[MAPNAME] [varchar](200) NULL,
	[SAVEGAME] [varchar](50) NULL,
 CONSTRAINT [PK_DMAP] PRIMARY KEY CLUSTERED 
(
	[MAP_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


