USE [DATA.MDF]
GO

/****** Object:  Table [dbo].[DNA]    Script Date: 11/24/2017 12:11:31 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DNA](
	[PARENT_ID] [char](32) NOT NULL,
	[GEN] [varchar](32) NOT NULL,
	[VALOR] [float] NULL,
 CONSTRAINT [PK_DNA] PRIMARY KEY CLUSTERED 
(
	[PARENT_ID] ASC,
	[GEN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


