USE [DATA.MDF]
GO

/****** Object:  Table [dbo].[DPLANT]    Script Date: 11/24/2017 12:11:53 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DPLANT](
	[aliveID] [char](32) NOT NULL,
	[PARENT_ID] [char](32) NULL,
	[CURRENTLIFECYCLE] [int] NULL,
	[GENERATION] [int] NULL,
	[SIZE] [int] NULL,
	[NEXTREPRODUCTIONCYCLE] [float] NULL,
	[WATERDEPOSIT] [float] NULL,
	[STATUS] [nchar](20) NULL,
 CONSTRAINT [PK_DPLANT] PRIMARY KEY CLUSTERED 
(
	[aliveID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


